# Generated by Django 3.2.8 on 2021-10-10 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=30)),
                ('pasw', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PubSubApp.categoria')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PubSubApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('cuerpo', models.TextField(max_length=1000)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PubSubApp.categoria')),
            ],
        ),
    ]
